eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes[0]:
        id: car-service
        uri: lb://car-service
        predicates[0]: Path=/api/car/**
      routes[1]:
        id: opinion-service
        uri: lb://opinion-service
        predicates[0]: Path=/api/opinion/**
      routes[2]:
        id: fuel-report-service
        uri: lb://fuel-report-service
        predicates[0]: Path=/api/fuel/**
      routes[3]:
        id: article-service
        uri: lb://article-service
        predicates[0]: Path=/api/article/**
      routes[4]:
        id: comment-service
        uri: lb://comment-service
        predicates[0]: Path=/api/comment/**
      routes[5]:
        id: discovery-server
        uri: http://localhost:8761
        predicates[0]: Path=/eureka/web
        filters[0]: SetPath=/
      routes[6]:
        id: discovery-server-static
        uri: http://localhost:8761
        predicates[0]: Path=/eureka/**
#server:
#  port: 8081