spring:
  application:
    name: article-service
  datasource:
    url: jdbc:mysql://localhost:3306/article_data?useSSL=false&serverTimezone=Europe/Warsaw
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka